### ISSUE TITLE
How to display results in new page?

### ISSUE THREAD

**Issue by jcyin1** [swiftype/swiftype-search-jquery#10]
Hello,

I'm using the Swiftype Jquery Plugin but I can't find the option to display search results in a new page, there only seems to be an option to display search results in an existing div in the current page.

Thanks

**Comment by jiwoochun** [comment]
Hi,

I'm trying to get this running on a wordpress website. I know there's a wordpress plugin but we're experiencing some problems with it so we are looking into using the jQuery version instead. Is there a way to provide some example code to redirect the search results to a different page ie `search-results.php`?
Any help would be greatly appreciated.
