### ISSUE TITLE
Unhelpful error if DocumentType isn't found

### ISSUE THREAD

**Issue by michaelrkn** [swiftype/swiftype-search-jquery#18]
I help maintain the Ember.js Guides. For each revision of the Guides we publish, we add a DocumentType for that revision to our Swiftype search engine. If the DocumentType isn't published (such as in development, or if something goes wrong in the publishing step), our search doesn't work and the error `Uncaught TypeError: Cannot read property 'query' of undefined` shows up in the browser console. 

A much more helpful error message is embedded in the response object from Swiftype - if you run `t.errors.document_types.MY_DOCUMENT_TYPE[0]` (where `MY_DOCUMENT_TYPE` is the unpublished DocumentType) in the scope where the exception was thrown, it returns `"No DocumentType found for slug 'MY_DOCUMENT_TYPE' for this engine."` It would be really nice if this text were errored to the console - it would make it much easier to track down the problem. 

I don't see an easy way to catch the exception from the jQuery plugins Swiftype offers, as the exception is thrown from http://s.swiftypecdn.com/assets/swiftype_nocode-5190fccc6a3c7dcff96a2c6aad0e53dd.js. Do you have any suggestions for a way to do this currently? Is there a repo I can open a PR against to implement this? Or is this something you folks would consider adding?

Thanks!

**Comment by yakhinvadim** [comment]
Archived due to age
