### ISSUE TITLE
`onComplete` callback or equivalent available?

### ISSUE THREAD

**Issue by acorncom** [swiftype/swiftype-search-jquery#19]
Howdy, we've run into a snag on the http://guides.emberjs.com site with this plugin (more details here: https://github.com/emberjs/guides/issues/514) and were wondering if you had any pointers on getting this working?

In essence, in addition to making a call to the `pingSearchResultClick` method, we'd also like the ability to adjust the url for the search result on the fly prior to the browser being redirected.  We're able to do that very smoothly with the [swiftype-autocomplete-jquery plugin](https://github.com/swiftype/swiftype-autocomplete-jquery) but don't see that it's supported with this plugin ...

Thoughts?  Thanks!

**Comment by thekaveman** [comment]
I haven't tried this myself, but it looks like [`onComplete` is an available option](https://github.com/swiftype/swiftype-search-jquery/blob/master/jquery.swiftype.search.js#L301) that you can override on initialization.

**Comment by yakhinvadim** [comment]
Archived due to age
