### ISSUE TITLE
Open clicked result links in new tab

### ISSUE THREAD

**Issue by mbernier** [swiftype/swiftype-search-jquery#23]
When our users click a link in the results list, they are always redirected within their current tab. 

How can we adjust the code so that it always opens in a new tab?

[I believe this line to be the culprit](https://github.com/swiftype/swiftype-search-jquery/blob/master/jquery.swiftype.search.js#L237), but I am not 100% sure and could use your help.

**Comment by amk221** [comment]
https://github.com/swiftype/swiftype-search-jquery/blob/master/jquery.swiftype.search.js#L57

**Comment by flickerbox-tom** [comment]
You can modify line #54 selectedCallback to look for a shift/control/meta key event with the click.

`$this.selectedCallback = function (data) {
        return function (e) {
          var $el = $(this);
          e.preventDefault();
          if (e.shiftKey || e.ctrlKey || e.metaKey) {
          		Swiftype.pingSearchResultClick(config.engineKey, data['id'], function() {
          			window.open($el.attr('href'), '_blank');      
          		});
          	}else{
          		Swiftype.pingSearchResultClick(config.engineKey, data['id'], function() {
          			window.location = $el.attr('href');
          		});
          	}
        };`

**Comment by yakhinvadim** [comment]
Archived due to age
