### ISSUE TITLE
Release for bower install

### ISSUE THREAD

**Issue by ardouglass** [swiftype/swiftype-search-jquery#24]
Currently when installing via bower, the dependency for this is `"swiftype-search-jquery": "swiftype-jquery#*"`. Could you please create a release of this plugin so we can include a specific version number in the event this plugin changes in a way that could break our build?

**Comment by JasonStoltz** [comment]
Sorry, this is a very late reply. Just trying to close out old issues.

 https://github.com/swiftype/swiftype-search-jquery/releases
