### ISSUE TITLE
Auto complete in search field is missing

### ISSUE THREAD

**Issue by megin1989** [swiftype/swiftype-search-jquery#40]
Default Swifttype search field supports autocomplete functionality. Is there any way to implement that functionality here?

**Comment by JasonStoltz** [comment]
Hi @megin1989. We have a separate plugin that can be used to implement an autocomplete input box. These two plugins can be used together.

https://github.com/swiftype/swiftype-autocomplete-jquery

**Comment by megin1989** [comment]
Thanks @JasonStoltz
