### ISSUE TITLE
Issue on Edge Browser

### ISSUE THREAD

**Issue by polepallesunil** [swiftype/swiftype-search-jquery#44]
If we use swiftype-search-jquery.js what we have in repository, we are not getting response/results from swiftype api. Issue primarily seeing on Edge and IE11 only. 

If we ajax it using api URL, it works fine. Hope we find solution for "swiftype-search-jquery.js" soon.

Regards
Sunil

**Comment by silas-miller** [comment]
@polepallesunil Just tested our swiftype jquery search and it is working in both Edge and IE11 . When you do a search do you see the Swiftype network request being sent?

**Comment by polepallesunil** [comment]
Nope. It's not sending request only.

**Comment by polepallesunil** [comment]
You can replicate it in https://www.akamai.com

**Comment by JasonStoltz** [comment]
@polepallesunil Is there an error message?

**Comment by polepallesunil** [comment]
I am not getting any error message. It's not sending request to api on Edge. It's working fine on Chrome and other browsers except IE11/Edge.

**Comment by silas-miller** [comment]
@polepallesunil The search page in both IE11 and Edge both throw a few unmatched HTML tag errors.

**Comment by JasonStoltz** [comment]
@polepallesunil I verified that this project does work in IE11. My best guess is whatever is going on is related to something else on your page. If there are unmatched html tags, or other javascript errors, they could be interfering with this.
