### ISSUE TITLE
Not working deployed

### ISSUE THREAD

**Issue by thebookofjedediah** [swiftype/swiftype-search-jquery#50]
Hi! This is an awesome library, I'm just having one issue with the custom search. When I use the custom.html file, it works locally, but as soon as I deploy it to Netlify, it no longer continues to work. Is there an easy workaround for this?

**Comment by yakhinvadim** [comment]
Hi! Do you see any errors in the browser console?

**Comment by thebookofjedediah** [comment]
It is an issue with Hogan.js not serving properly - not sure the fix yet (it isn't recognizing the HTTPS I think) but I'll update this if I get backt o it
